### ISSUE TITLE
Call to undefined function App\Http\Controllers\getDetails()

### ISSUE THREAD

**Issue by nomanmarwat** [salis77/Laravel-instagram-account-data-without-api#2]
"Call to undefined function App\Http\Controllers\getDetails() " why i am getting this error as I did exactly you did??

**Comment by nomanmarwat** [comment]
@alisalmabadi please consider this issue. Thanks

**Comment by alisalmabadi** [comment]
even though I created this project about 2 years ago, but I tested it and there was not problem for me

did you run composer install?
it seems that helpers.php functions is not loading in your project, so getDetails() method is undefiend for you
I edited helpers.php right now hope be helpful
 pull it
